### ISSUE TITLE
Reduce float number decimal points

### ISSUE THREAD

**Issue by rammazzoti2000** [nyatindopatrick/math-magicians#3]
Hello Patrick :wave: ,

I was looking over in the `src/components/Calculator.js` and I tried the `https://calculator-reac-app.netlify.app/` calculator.
Don't know if the calc app is yours, but it seems that making a division operation like `(9 ÷ 3.3)` gives you a big float number that's overflowing outside the results screen.

I don't know if is relevant (I apologize if it isn't), but you could reduce it by using `parseFloat()`, e.g. `parseFloat().toFix(5)`.
There are also other solutions [check them out](https://stackoverflow.com/questions/11832914/round-to-at-most-2-decimal-places-only-if-necessary).

![image](https://user-images.githubusercontent.com/3244654/110177043-9b92f300-7e04-11eb-9cc8-333e584c1806.png)

**Comment by nyatindopatrick** [comment]
Hi Alex,
Thanks for your keen eye. The bug's fixed.
